#! /bin/bash
#=====================================================================
# postinst script
# This script executes after unpacking files from that archive and registering the product at the depot.
#
# The following environment variables can be used to obtain information about the current installation:
#   PRODUCT_ID: id of the current product
#   CLIENT_DATA_DIR: directory which contains the installed client data
#=====================================================================
# J. Boettge <boettge@mpi-halle.mpg.de>  2017-06-27 11:17:18 +0200
#=====================================================================

LOGFILE=/tmp/${PRODUCT_ID}__opsi_package_install.log

exec >> $LOGFILE
exec 2>&1
chgrp opsiadmin $LOGFILE
chmod g+rw $LOGFILE

echo "=================================================="
echo "${PRODUCT_ID} POSTINST LOG"
echo "=================================================="

SRC="${CLIENT_DATA_DIR}/../../source/${PRODUCT_ID##0_}"
DST="${CLIENT_DATA_DIR}/files"
# remove trailing "/" in path:
DST=${DST%\/}
ERR=0

### check for testing and DFN package:
P=${PRODUCT_ID}
[ "${P}" = "${P##0_}" ] &&  IS_TESTING=false || IS_TESTING=true
P=${P/#0_/}
[ "${P}" = "${P##dfn_}" ] && IS_DFN=false || IS_DFN=true


if [ $IS_DFN == true ]; then
	 [ ! -d "${DST}" ] && mkdir $DST
else
	### symlink files directory to ../../source/${PRODUCT_ID##0_} only
	### for non-DFN packages:
	if [ -h "${DST}" ]; then
		echo "Symlink to [${DST}] already exists. - Replacing"
		rm ${DST}
	fi

	if [ -d "${DST}" ]; then
		echo "Directory [${DST}] already exists!\nSkipping creation of symlink."
	elif [ -f "${DST}" ]; then
		echo "File [${DST}] already exists!\nSkipping creation of symlink."
	else
		ln -s ${SRC} ${DST}
	fi
fi


### restore custom directories
TMP_DIR=${CLIENT_DATA_DIR}/../${PRODUCT_ID}.tmp
if [ -d $TMP_DIR ]; then
	echo 'Restoring previous directories...'
	
	for DIRNAME in custom files; do
		echo "* [${DIRNAME}]"
		if [ -d $TMP_DIR/${DIRNAME} ]; then
			test -e $CLIENT_DATA_DIR/${DIRNAME} && rm -rf $CLIENT_DATA_DIR/${DIRNAME}
			echo -e "\tmoving $TMP_DIR/${DIRNAME} to $CLIENT_DATA_DIR/"
			mv $TMP_DIR/${DIRNAME} $CLIENT_DATA_DIR/ || exit 1	
		else
			echo -e "\tdoes not exist here"
		fi
	done
fi
echo "Removing temporary files..."
rm -rf $TMP_DIR


### download files form vendor:
#https://downloads.vivaldi.com/stable/Vivaldi.1.10.867.42.exe
#https://downloads.vivaldi.com/stable/Vivaldi.1.10.867.42.x64.exe

VERSION=`opsi-admin -dS method getProduct_hash ${PRODUCT_ID} | grep productVersion | cut -d "=" -f 2`
BASE="https://downloads.vivaldi.com/stable/"

echo "Detected version for this package: ${VERSION}"

CNT=0
for ARCH in "exe" "x64.exe"; do
	PACKAGE="Vivaldi.${VERSION}.${ARCH}"
	let "CNT++"
	echo "Retrieving [$PACKAGE]";
	if [ -f "${DST}/${PACKAGE}" ]; then
		echo -e "\tfile already exists"
	else
		wget -nv "${BASE}/${PACKAGE}" -O "${DST}/${PACKAGE}"
		[ ! -s "${DST}/${PACKAGE}" ] && let "ERR+=1<<$CNT"
	fi
done
exit $ERR
